### ISSUE TITLE
[Minor] The Cruisers steering wheel does not sync to other clients

### ISSUE THREAD

**Issue by ScandalTheVandal** [digger1213/CruiserImproved#2]
Slightly nitpicky but something I did notice, for anyone who's not the driver, regardless if they have this mod installed or not, will still see the steering wheel desync'd on their end.

Additionally, there also appears to be an issue where only the hand animations of turning the wheel play for other clients while the vehicle is stationary/not moving at all, the wheel will desync further if you start moving and start turning any direction, whether this is related to the problem above I've no idea

**Comment by ScandalTheVandal** [comment]
I've also noticed that the steering wheel (except its animations) do not update if the Cruiser is _not moving_ if that helps

**Comment by digger1213** [comment]
I've noticed this too and looked into it, unfortunately it's not an easy fix and I don't think it's possible without requiring all players to have the mod. 

The RPC the game uses to sync the steering angle (`VehicleController.SyncCarPositionClientRpc`) only sends steering control input instead of the actual wheel position, and only every time the car is moved a certain distance from it's last spot. This just isn't enough information to attempt to synchronize the steering angle over the network. 

Could be done by requiring other players to also use this mod but currently the goal is to keep this mod clientside.

**Comment by ScandalTheVandal** [comment]
> I've noticed this too and looked into it, unfortunately it's not an easy fix and I don't think it's possible without requiring all players to have the mod.
> 
> The RPC the game uses to sync the steering angle (`VehicleController.SyncCarPositionClientRpc`) only sends steering control input instead of the actual wheel position, and only every time the car is moved a certain distance from it's last spot. This just isn't enough information to attempt to synchronize the steering angle over the network.
> 
> Could be done by requiring other players to also use this mod but currently the goal is to keep this mod clientside.

Yeah, I even tried to look into it a little myself although I am no coder, and I suppose it's fair if the goal is to keep it as client-sided as possible

**Comment by digger1213** [comment]
This has been implemented in v1.2.0 with the addition of synced configs and networking. If both host and client have the mod, the steering wheel will now sync properly.
